<template>
  <div class="page">
      <h1>Terms & Conditions</h1>
      <h3>BUSINESS SERVICES CUSTOMER TERMS AND CONDITIONS</h3>    
<p>
The Customer named on the Trepyx Business Service Order Agreement and Trepyx Telecom “Trepyx” agree that the terms and conditions on the Trepyx Business Service Order Agreement and these terms and conditions constitute the agreement (the “Agreement”) for the provision of the Services selected by Customer and designated on a Service Order. Services may include Trepyx Business and Hospitality commercial high-speed internet services (“Internet”) and Trepyx Business and Hospitality commercial digital voice services, including enhanced voice, toll free and trunk services (“Voice”) (each a “Service” and collectively “Services”).
The terms and conditions in the “GENERAL TERMS AND CONDITIONS” section below are applicable to all Services. Additional terms and conditions apply to the Internet and the Voice Service and should be reviewed in either the “ADDITIONAL TERMS APPLICABLE TO INTERNET SERVICE” section, or the “ADDITIONAL TERMS APPLICABLE TO VOICE SERVICE” section, as applicable.
</p>
<h4>GENERAL TERMS AND CONDITIONS</h4>   

<h5>ARTICLE 1. DEFINITIONS</h5>  
<p>
Affiliate: Any entity that controls, is controlled by or is under common control with Trepyx.
Agreement: These terms and conditions and the Service Order Agreement executed by Customer.
Trepyx Equipment: Any and all facilities, equipment or devices provided by Trepyx or its authorized contractors at the Service Location(s) that are used to deliver any of the Services including, but not limited to, all terminals, wires, modems, lines, circuits, ports, routers, gateways, switches, channel service units, data service units, cabinets, and racks. Notwithstanding the above, inside telephone wiring, whether or not installed by Trepyx, shall not be considered Trepyx Equipment.
Confidential Information: All information regarding either party’s business which has been marked or is otherwise communicated as being “proprietary” or “confidential.” or which reasonably should be known by the receiving party to be proprietary or confidential information. Without limiting the generality of the foregoing, Confidential Information shall include, even if not marked, the Agreement, all Licensed Software, promotional materials, proposals, quotes, rate information, discount information, subscriber information, network upgrade information and schedules, network operation information (including without limitation information about outages and planned maintenance) and invoices, as well as the parties’ communications regarding such items.
Customer-Provided Equipment: Any and all facilities, equipment or devices supplied by Customer for use in connection with the Services.
Licensed Software: Computer software or code provided by Trepyx or required to use the Services, including without limitation, associated documentation, and all updates thereto.
Party: A reference to Trepyx or the Customer; and in the plural, a reference to both companies.
Service(s): The Internet, Toll Free Trunk and Voice services provided by Trepyx to Customer described in one or more Service Order(s). All Services are for commercial use only, except as otherwise expressly permitted herein.
Service Commencement Date: The date(s) on which Trepyx first makes Service available for use by Customer. A single Service Order containing multiple Service Locations or Services may have multiple Service Commencement Dates.
Service Order: A request for Trepyx to provide the Services to Service Location(s) submitted by Customer to Trepyx (a) on a then-current Trepyx form designated for that purpose or (b) if available, through a Trepyx electronic order processing system designated for that purpose.
Service Order Agreement: The agreement under which all Service Orders are submitted to Trepyx.
Service Location(s): The Customer location(s) where Trepyx provides the Services.
Service Term: The duration of time (commencing on the Service Commencement Date) for which Services are ordered, as specified in a Service Order.
Tariff: A federal or state Trepyx tariff and the successor documents of general applicability that replace such tariff in the event of detariffing.
Termination Charges: Charges that may be imposed by Trepyx if, prior to the end of the applicable Service Term (a) Trepyx terminates Services for cause or (b) Customer terminates Services without cause. Termination Charges with respect to each terminated Service Order shall equal, in addition to all amounts payable by Customer in accordance with Section 5.3, seventy-five percent (75%) of the remaining monthly fees that would have been payable by Customer under the Service Order if the Services described in the Service Order had been provided until the end of the Service Term. In the event the Agreement is terminated as herein described during the initial Service Term, Termination Charges shall also include one hundred percent (100%) of any amount paid by Trepyx in connection with Custom Installation, as that term is defined in Section 2.7, for the Services provided by Trepyx under the Service Order.
</p>
<h5>ARTICLE 2. DELIVERY OF SERVICES</h5>  
<p>
2.1 Orders. Customer shall submit to Trepyx a properly completed Service Order to initiate Services to a Service Location(s). A Service Order shall become binding on the parties when (i) it is specifically accepted by Trepyx either electronically or in writing, (ii) Trepyx begins providing the Services described in the Service Order or (iii) Trepyx begins Custom Installation (as defined in Section 2.7) for delivery of the Services described in the Service Order, whichever is earlier. When a Service Order becomes effective it shall be deemed part of, and shall be subject to, the Agreement.
2.2 Speed. Trepyx makes no representation regarding the speed of the Internet Service. Actual speeds may vary and are not guaranteed. Many factors affect speed including, without limitation, the number of workstations using a single connection.
2.3 Access. Customer, at no cost to Trepyx, shall secure and maintain all necessary rights of access to Service Location(s) for Trepyx to install and provide the Services, unless Trepyx has secured such access prior to this Agreement. In addition, Customer shall provide an adequate environmentally controlled space and such electricity as may be required for installation, operation, and maintenance of the Trepyx Equipment used to provide the Services within the Service Location(s). Trepyx and its employees and authorized contractors will require free ingress and egress into and out of the Service Location(s) in connection with the provision of Services. Upon reasonable notice from Trepyx, Customer shall provide all required access to Trepyx and its authorized personnel.
2.4 Service Commencement Date. Upon installation and connection of the necessary facilities and equipment to provide the Services, or in the case of Voice, the day Voice Service is activated, Trepyx shall notify Customer that the Services are available for use, and the date of such notice shall be called the “Service Commencement Date.” Any failure or refusal on the part of Customer to be ready to receive the Services on the Service Commencement Date shall not relieve Customer of its obligation to pay applicable Service charges.
2.5 Trepyx Equipment. Trepyx Equipment is and shall remain the property of Trepyx regardless of where installed within the Service Location(s), and shall not be considered a fixture or an addition to the land or the Service Location(s). At any time Trepyx may remove or change Trepyx Equipment in its sole discretion in connection with providing the Services. Customer shall not move, rearrange, disconnect, remove, attempt to repair, or otherwise tamper with any Trepyx Equipment or permit others to do so, and shall not use the Trepyx Equipment for any purpose other than that authorized by the Agreement. Trepyx shall maintain Trepyx Equipment in good operating condition during the term of this Agreement; provided, however, that such maintenance shall be at Trepyx’s expense only to the extent that it is related to and/or resulting from the ordinary and proper use of the Trepyx Equipment. Customer is responsible for damage to, or loss of, Trepyx Equipment caused by its acts or omissions, and its noncompliance with this Section, or by fire, theft or other casualty at the Service Location(s), unless caused by the negligence or willful misconduct of Trepyx. Customer agrees not to take any action that would directly or indirectly impair Trepyx’s title to the Trepyx Equipment, or expose Trepyx to any claim, lien, encumbrance, or legal process, except as otherwise agreed in writing by the Parties. Following Trepyx’s discontinuance of the Services to the Service Location(s), Trepyx retains the right to remove the Trepyx Equipment including, but not limited to, that portion of the Trepyx Equipment located within the Service Location(s). To the extent Trepyx removes such Trepyx Equipment, it shall be responsible for returning the Service Location(s) to its prior condition, wear and tear excepted.
2.6 Customer-Provided Equipment. Trepyx shall have no obligation to install, operate, or maintain Customer-Provided Equipment. Customer alone shall be responsible for providing maintenance, repair, operation and replacement of all inside telephone wiring and equipment and facilities on the Customer’s side of the cable modem, route and/or coaxial input connection. All Customer-Provided Equipment and wiring that Customer uses in connection with the Services must be fully compatible with the Services. Customer shall be responsible for the payment of all charges for troubleshooting, maintenance or repairs attempted or performed by Trepyx’s employees or authorized contractors when the difficulty or trouble report results from Customer-Provided Equipment.
2.7 Engineering Review. Each Service Order submitted by Customer shall be subject to an engineering review by Trepyx. The engineering review will determine whether the cable plant must be extended, built or upgraded in order to provide the ordered Services at the requested Service Location(s), or whether Service installation has to be expedited to meet the Customer’s requested Service Commencement Date (”Custom Installation”) . Trepyx will provide Customer written notification in the event Service installation at any Service Location will require an additional one-time installation fee (“Custom Installation Fee”). Customer will have five (5) days from receipt of such notice to reject the Custom Installation Fee and terminate, without further liability, the Service Order with respect to the affected Service Location(s).
2.8 Administrative Web Site. Trepyx may, at its sole option, make one or more administrative web sites available to Customer in connection with Customer’s use of the Services (each an “Administrative Web Site”). Trepyx may furnish Customer with one or more user identifications and/or passwords for use on the Administrative Web Site. Customer shall be responsible for the confidentiality and use of such user identifications and/or passwords and shall immediately notify Trepyx if there has been an unauthorized release, use or other compromise of any user identification or password. In addition, Customer agrees that its authorized users shall keep confidential and not distribute any information or other materials made available by the Administrative Web Site. Customer shall be solely responsible for all use of the Administrative Web Site, and Trepyx shall be entitled to rely on all Customer uses of and submissions to the Administrative Web Site as authorized by Customer. Trepyx shall not be liable for any loss, cost, expense or other liability arising out of any Customer use of the Administrative Web Site or any information on the Administrative Web Site. Trepyx may change or discontinue the Administrative Web Site, or Customer’s right to use the Administrative Web Site, at any time. Additional terms and policies may apply to Customer’s use of the Administrative Web Site. These terms and policies will be posted on the site.
</p>
<h5>ARTICLE 3. CHARGES, BILLING AND PAYMENT</h5>  
<p>
3.1 Charges. Customer shall pay Trepyx one hundred percent (100%) of the Custom Installation Fee prior to the installation of Service. Customer further agrees to pay all charges associated with the Services, as set forth or referenced in the applicable Service Order(s) or invoiced by Trepyx. These charges may include, but are not limited to installation charges, monthly recurring service charges, usage charges including without limitation charges for the use of Trepyx Equipment, per-call charges, charges for service calls, maintenance and repair charges, and applicable federal, state, and local taxes, fees, surcharges and recoupments (however designated). Some Services such as measured and per-call charges, (as explained below in the Voice Additional Terms) may be invoiced after the Service has been provided to Customer. Except as otherwise indicated herein or on the applicable Service Order(s), monthly recurring charges for Internet Services shall not increase during the initial Service Term. 
3.2 Third-Party Charges. Customer may incur charges from third party service providers that are separate and apart from the amounts charged by Trepyx. These may include, without limitation, charges resulting from accessing on-line services, calls to parties who charge for their telephone based services, purchasing or subscribing to other offerings via the Internet or interactive options on Public View Video, Video, or otherwise. Customer agrees that all such charges, including all applicable taxes, are Customer’s sole responsibility. In addition, Customer is solely responsible for protecting the security of credit card information provided to others in connection with such transactions.
3.3 Payment of Bills. Except as otherwise indicated herein or on the Service Order(s), Trepyx will invoice Customer in advance on a monthly basis for all monthly recurring Service charges and fees arising under the Agreement. All other charges will be billed monthly in arrears. Customer shall make payment to Trepyx for all invoiced amounts within thirty (30) days after the date of the invoice. Any amounts not paid to Trepyx within such period will be considered past due. If a Service Commencement Date is not the first day of a billing period, Customer’s next monthly invoice shall include a pro-rated charge for the Services, from the date of installation to the first day of the new billing. In certain cases, Trepyx may agree to provide billing services on behalf of third parties, as the agent of the third party. Any such third-party charges shall be payable pursuant to any contract or other arrangement between Customer and the third party. Trepyx shall not be responsible for any dispute regarding these charges between Customer and such third party. Customer must address all such disputes directly with the third party.
3.4 Partial Payment. Partial payment of any bill will be applied to the Customer’s outstanding charges in the amounts and proportions as solely determined by Trepyx. No acceptance of partial payment(s) by Trepyx shall constitute a waiver of any rights to collect the full balance owed under the Agreement.
3.5 Payment by Credit Card. Upon Customer’s written request and Trepyx’s acceptance of such request, Trepyx will accept certain credit card payments for charges generated under the Agreement. By providing Trepyx with a credit card number, Customer authorizes Trepyx to charge the card for all charges generated under this Agreement, until (i) this Agreement is terminated or (ii) Customer provides sixty (60) days prior notice that Trepyx stop charging the credit card. Customer agrees to provide Trepyx with updated credit card or alternate payment information on a timely basis prior to the expiration or termination of the credit card on file or in the event that Customer’s credit card limit is or will be insufficient to cover payment. If Trepyx is unable to charge Customer's credit card for any reason, Customer agrees to pay all amounts due, including any late payment charges or bank charges, upon demand by Trepyx. Trepyx may limit the option to pay by credit card to specific Services or may discontinue acceptance of credit card payments in whole or in part upon thirty (30) days prior notice to Customer.
3.6 Credit Approval and Deposits. Initial and ongoing delivery of Services may be subject to credit approval. Customer shall provide Trepyx with credit information requested by Trepyx. Customer authorizes Trepyx to make inquiries and to receive information about Customer’s credit history from others and to enter this information in Customer’s records. Customer represents and warrants that all credit information that it provides to Trepyx will be true and correct. Trepyx, in its sole discretion, may deny the Services based upon an unsatisfactory credit history. Additionally, subject to applicable regulations, Trepyx may require Customer to make a deposit (in an amount not to exceed an estimated two-month's charge for the Services) as a condition to Trepyx’s provision of the Services, or as a condition to Trepyx’s continuation of the Services. The deposit will not, unless explicitly required by law, bear interest and shall be held by Trepyx as security for payment of Customer's charges. If the provision of Service to Customer is terminated, or if Trepyx determines in its sole discretion that such deposit is no longer necessary, then the amount of the deposit will be credited to Customer's account or will be refunded to Customer, as determined by Trepyx.
3.7 Taxes and Fees. Customer shall be responsible for the payment of any and all applicable local, state, and federal taxes or fees (however designated). Customer will be responsible to pay any Service fees, payment obligations and taxes that become applicable retroactively.
3.8 Other Government-Related Costs and Fees. Trepyx reserves the right to invoice Customer for any fees or payment obligations in connection with the Services imposed by governmental or quasi-governmental bodies in connection with the sale, installation, use, or provision of the Services, including, without limitation, applicable franchise fees (if any), regardless of whether Trepyx or its Affiliates pay the taxes directly or are required by an order, rule, or regulation of a taxing jurisdiction to collect them from Customer.. These obligations may include those imposed on Trepyx or its affiliates by an order, rule, or regulation of a regulatory body or a court of competent jurisdiction, as well as those that Trepyx or its affiliates are required to collect from the Customer or to pay to others in support of statutory or regulatory programs. For example, Voice customers are charged a monthly regulatory recovery fee to help defray Trepyx’s contributions to municipal, state, and federal programs including, without limitation, universal service, telecom relay services for the visually/hearing impaired, and 911/E911 programs and infrastructure. This regulatory recovery fee is not a tax, and it is not government-mandated. Taxes and other government-related fees and surcharges may be changed with or without notice,
3.9 Disputed Invoice. If Customer disputes any portion of an invoice, Customer must pay the undisputed portion of the invoice and submit a written claim, including all documentation substantiating Customer’s claim, to Trepyx for the disputed amount of the invoice by the invoice due date. The Parties shall negotiate in good faith to resolve the dispute. However, should the parties fail to mutually resolve the dispute within sixty (60) days after the dispute was submitted to Trepyx, all disputed amounts shall become immediately due and payable to Trepyx.
3.10 Past-Due Amounts. Any undisputed payment not made when due will be subject to a reasonable late charge not to exceed the highest rate allowed by law on the unpaid invoice. If Customer’s account is delinquent, Trepyx may refer the account to a collection agency or attorney that may pursue collection of the past due amount and/or any Trepyx Equipment that Customer fails to return in accordance with the Agreement. If Trepyx is required to use a collection agency or attorney to collect any amount owed by Customer or any unreturned Trepyx Equipment, Customer agrees to pay all reasonable costs of collection or other action. The remedies set forth herein are in addition to and not in limitation of any other rights and remedies available to Trepyx under the Agreement or at law or in equity.
3.11 Rejected Payments. Except to the extent otherwise prohibited by law, Customer will be assessed a service charge up to the full amount permitted under applicable law for any check or other instrument used to pay for the Services that has been rejected by the bank or other financial institution.
3.12 Fraudulent Use of Services. Customer is responsible for all charges attributable to Customer with respect to the Services, even if incurred as the result of fraudulent or unauthorized use of the Services. Trepyx may, but is not obligated to, detect or report unauthorized or fraudulent use of Services to Customer. Trepyx reserves the right to restrict, suspend or discontinue providing any Service in the event of fraudulent use by Customer.
</p>
<h5>ARTICLE 4. TERM</h5>  
<p>
4.1 Agreement Term. This Agreement shall terminate upon the expiration or other termination of the final existing Service Order entered into under this Agreement. The term of a Service Order shall commence on the Service Commencement Date and shall terminate at the end of the stated Service Term of such Service. Unless otherwise stated in these terms and conditions, if a Service Order does not specify a term of service, the Service Term shall be one (1) year from the Service Commencement Date.
4.2 Service Order Renewal. Upon the expiration of the Service Term, this Agreement and each applicable Service Order shall automatically renew for successive periods of one (1) year each (“Renewal Term(s)”), unless otherwise stated in these terms and conditions or prior notice of non-renewal is delivered by either Party to the other at least thirty (30) days before the expiration of the Service Term or the then current Renewal Term, or in the case of Louisiana Customers, notice of non-renewal is delivered to Trepyx within thirty (30) days following the expiration of the Service Term or the then current Renewal Term. Except as otherwise identified in the Agreement, at any time during initial Service Term and from time to time thereafter, Trepyx may increase the charges for Voice Services subject to thirty (30) days prior notice to Customer. Effective at any time after the end of the initial Service Term and from time to time thereafter, Trepyx may modify the charges for Internet Services subject to thirty (30) days prior notice to Customer. Customer will have thirty (30) days from receipt of such notice to cancel the applicable Service without further liability. Should Customer fail to cancel within this timeframe, Customer will be deemed to have accepted the modified Service pricing.
</p>
<h5>ARTICLE 5. TERMINATION OF AGREEMENT AND/OR A SALES ORDER</h5>  
<p>
5.1 Termination for Convenience. Notwithstanding any other term or provision in this Agreement, Customer shall have the right to terminate a Service Order, or this Agreement in whole or part, at any time during the Service Term upon sixty (60) days prior notice to Trepyx, and subject to payment to Trepyx of all outstanding amounts due for the Services, any and all applicable Termination Charges, and the return of any and all Trepyx Equipment.
5.2 Termination for Cause.
(a) If Customer is in breach of a payment obligation (including failure to pay a required deposit), and fails to make payment in full within ten (10) days after receipt of notice of default, or has failed to make payments of all undisputed charges on or before the due date on three (3) or more occasions during any twelve (12) month period, Trepyx may, at its option, terminate this Agreement, terminate the affected Service Orders, suspend Service under the affected Service Orders, and/or require a deposit, advance payment, or other satisfactory assurances in connection with any or all Service Orders as a condition of continuing to provide the Services. However, Trepyx will not take any such action as a result of Customer’s non-payment of a charge that is the subject of a timely billing dispute, unless the parties have reviewed the dispute and determined in good faith that the charge is correct.
(b) If either party breaches any material term of this Agreement and the breach continues without remedy for thirty (30) days after notice of default, the non-defaulting party may terminate for cause any Service Order materially affected by the breach.
(c) A Service Order may be terminated by either party immediately upon notice if the other party has become insolvent or involved in liquidation or termination of its business, or adjudicated bankrupt, or been involved in an assignment for the benefit of its creditors.
(d) Termination by either party of a Service Order does not waive any other rights or remedies that it may have under this Agreement.
5.3 Effect of Expiration or Termination of the Agreement or a Service Order. Upon the expiration or termination of a Service Order for any reason: (i) Trepyx may disconnect the applicable Service; (ii) Trepyx may delete all applicable data, files, electronic messages, voicemail or other information stored on Trepyx’s servers or systems; (iii) if Customer has terminated the Service Order prior to the expiration of the Service Term for convenience, or if Trepyx has terminated the Service Order prior to the expiration of the Service Term as a result of material breach by Customer, Trepyx may assess and collect from Customer applicable Termination Charges; (iv) Customer shall, permit Trepyx access to retrieve from the applicable Service Locations any and all Trepyx Equipment (however, if Customer fails to permit access, or if the retrieved Trepyx Equipment has been damaged and/or destroyed other than by Trepyx or its agents, normal wear and tear excepted, Trepyx may invoice Customer for the full replacement cost of the relevant Trepyx Equipment, or in the event of minor damage to the retrieved Trepyx Equipment, the cost of repair, which amounts shall be immediately due and payable); and (v) if used in conjunction with the terminated Service, Customer’s right to use applicable Licensed Software shall automatically terminate, and Customer shall be obligated to return the Licensed Software to Trepyx.
5.4 Regulatory and Legal Changes. The parties acknowledge that the respective rights and obligations of each party as set forth in this Agreement upon its execution are based on law and the regulatory environment as it exists on the date of execution of this Agreement. Trepyx may, in its sole discretion, immediately terminate this Agreement, in whole or in part, in the event there is a material change in any law, rule, regulation, Force Majeure event, or judgment of any court or government agency, and that change affects Trepyx’s ability to provide the Services herein.
</p>
<h5>ARTICLE 6. LIMITATION OF LIABILITY; DISCLAIMER OF WARRANTIES; WARNINGS</h5>  
<p>
6.1 NEITHER PARTY WILL BE LIABLE TO THE OTHER FOR ANY INCIDENTAL, INDIRECT, SPECIAL, PUNITIVE OR CONSEQUENTIAL DAMAGES, WHETHER OR NOT FORESEEABLE, OF ANY KIND INCLUDING BUT NOT LIMITED TO ANY LOSS REVENUE, LOSS OF USE, LOSS OF BUSINESS OR LOSS OF PROFIT, WHETHER SUCH ALLEGED LIABILITY ARISES IN CONTRACT OR TORT, PROVIDED, HOWEVER, THAT NOTHING HEREIN IS INTENDED TO LIMIT CUSTOMER’S LIABILITY FOR AMOUNTS OWED FOR THE SERVICES, FOR ANY EQUIPMENT OR SOFTWARE PROVIDED BY Trepyx OR FOR EARLY TERMINATION CHARGES. EXCEPT AS OTHERWISE EXPRESSLY PROVIDED IN THIS AGREEMENT, THE ENTIRE LIABILITY OF Trepyx AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AFFILIATES, AGENTS, SUPPLIERS OR CONTRACTORS (“ASSOCIATED PARTIES”) FOR LOSS, DAMAGES AND CLAIMS ARISING OUT OF THE DELIVERY OF THE SERVICES INCLUDING, BUT NOT LIMITED TO, DELAY IN THE INSTALLATION OF SERVICES OR THE PERFORMANCE OR NONPERFORMANCE OF THE SERVICES OR THE Trepyx EQUIPMENT SHALL BE LIMITED TO A SUM EQUIVALENT TO THE APPLICABLE OUT-OF-SERVICE CREDIT. REMEDIES UNDER THIS AGREEMENT ARE EXCLUSIVE AND LIMITED TO THOSE EXPRESSLY DESCRIBED IN THIS AGREEMENT.
6.2 THERE ARE NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON- INFRINGEMENT WITH RESPECT TO THE SERVICES, Trepyx EQUIPMENT, OR LICENSED SOFTWARE. ALL SUCH WARRANTIES ARE HEREBY EXPRESSLY DISCLAIMED TO THE MAXIMUM EXTENT ALLOWED BY LAW. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, Trepyx DOES NOT WARRANT THAT THE SERVICES, Trepyx EQUIPMENT, OR LICENSED SOFTWARE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF LATENCY OR DELAY, OR THAT THE SERVICES, Trepyx EQUIPMENT, OR LICENSED SOFTWARE WILL MEET YOUR REQUIREMENTS, OR THAT THE SERVICES, Trepyx EQUIPMENT, OR LICENSED SOFTWARE WILL PREVENT UNAUTHORIZED ACCESS BY THIRD PARTIES.
6.3 Trepyx MAKES NO WARRANTIES OR REPRESENTATIONS WITH RESPECT TO THE SERVICES, Trepyx EQUIPMENT, OR LICENSED SOFTWARE FOR USE BY THIRD PARTIES.
6.4 IN NO EVENT SHALL Trepyx, OR ITS ASSOCIATED PARTIES, SUPPLIERS, CONTRACTORS OR LICENSORS BE LIABLE FOR ANY LOSS, DAMAGE OR CLAIM ARISING OUT OF OR RELATED TO: (i) STORED, TRANSMITTED, OR RECORDED DATA, FILES, OR SOFTWARE; (ii) ANY ACT OR OMISSION OF CUSTOMER, ITS USERS OR THIRD PARTIES; (iii) INTEROPERABILITY,  INTERACTION OR INTERCONNECTION OF THE SERVICES WITH APPLICATIONS, EQUIPMENT, SERVICES OR NETWORKS PROVIDED BY CUSTOMER OR THIRD PARTIES; OR (iv) LOSS OR DESTRUCTION OF ANY CUSTOMER HARDWARE, SOFTWARE, FILES OR DATA RESULTING FROM ANY VIRUS OR OTHER HARMFUL FEATURE OR FROM ANY ATTEMPT TO REMOVE IT.
6.5 DISRUPTION OF SERVICE. Trepyx shall not be liable for any inconvenience, loss, liability, or damage resulting from any interruption of the Services, directly or indirectly caused by, or proximately resulting from, any circumstances, including, but not limited to, causes attributable to Customer or Customer- Equipment; inability to obtain access to the Service Locations; loss of use of poles or other utility facilities; strike; labor dispute; riot or insurrection; war; explosion; malicious mischief; fire, flood, lightening, earthquake, wind, ice, extreme weather conditions or other acts of God; failure or reduction of power; or any court order, law, act or order of government restricting or prohibiting the operation or delivery of the Services.
6.6 Customer’s sole and exclusive remedies under this Agreement are as expressly set forth in this Agreement. Certain of the above exclusions may not apply if the state in which a Service is provided does not allow the exclusion or limitation of implied warranties or does not allow the limitation or exclusion of incidental or consequential damages. In those states, the liability of Trepyx and its affiliates and agents is limited to the maximum extent permitted by law.
</p>
<h5>ARTICLE 7. INDEMNIFICATION</h5>  
<p>
7.1 Subject to Article 6, each Party (“Indemnifying Party”) will indemnify and hold harmless the other Party (“Indemnified Party”), its affiliates, officers, directors, employees, stockholders, partners, providers, independent contractors and agents from and against any and all joint or several costs, damages, losses, liabilities, expenses, judgments, fines, settlements and any other amount of any nature, including reasonable fees and disbursements of attorneys, accountants, and experts, arising from any and all claims, demands, actions, suits, or proceedings whether civil, criminal, administrative, or investigative (collectively, "Claims") relating to: (i) any Claim of any third party resulting from the negligence or willful act or omission of Indemnifying Party arising out of or related to the Agreement, the obligations hereunder, and uses of Services, Trepyx Equipment, and Licensed Software; and (ii) any Claim of any third party alleging infringement of a U.S. patent or U.S. copyright arising out of or related to this Agreement, the obligations hereunder, and the use of Services, Trepyx Equipment, and Licensed Software.
7.2 The Indemnifying Party agrees to defend the Indemnified Party for any loss, injury, liability, claim or demand (“Actions”) that is the subject of Article 7 hereof. The Indemnified Party agrees to notify the Indemnifying Party promptly, in writing, of any Actions, threatened or actual, and to cooperate in every reasonable way to facilitate the defense or settlement of such Actions. The Indemnifying Party shall assume the defense of any Action with counsel of its own choosing, but which is reasonably satisfactory to the Indemnified Party. The Indemnified Party may employ its own counsel in any such case, and shall pay such counsel’s fees and expenses. The Indemnifying Party shall have the right to settle any claim for which indemnification is available; provided, however, that to the extent that such settlement requires the Indemnified Party to take or refrain from taking any action or purports to obligate the Indemnified Party, then the Indemnifying Party shall not settle such claim without the prior written consent of the Indemnified Party, which consent shall not be unreasonably withheld, conditioned or delayed.
</p>
<h5>ARTICLE 8. SOFTWARE & SERVICES</h5>  
<p>
8.1 License. If and to the extent Customer requires the use of Licensed Software in order to use the Services supplied under any Service Order, Customer shall have a personal, nonexclusive, nontransferable, and limited license to use the Licensed Software in object code only and solely to the extent necessary to use the applicable Service during the corresponding Service Term. Customer may not claim title to, or an ownership interest in, any Licensed Software (or any derivations or improvements thereto) and Customer shall execute any documentation reasonably required by Trepyx, including, without limitation, end-user license agreements for the Licensed Software. Trepyx and its suppliers shall retain ownership of the Licensed Software, and no rights are granted to Customer other than a license to use the Licensed Software under the terms expressly set forth in this Agreement.
8.2 Restrictions. Customer agrees that it shall not: (i) copy the Licensed Software (or any upgrades thereto or related written materials) except for emergency back-up purposes or as permitted by the express written consent of Trepyx; (ii) reverse engineer, decompile, or disassemble the Licensed Software; (iii) sell, lease, license, or sublicense the Licensed Software; or (iv) create, write, or develop any derivative software or any other software program based on the Licensed Software.
8.3 Updates. Customer acknowledges that the use of the Services may periodically require updates and/or changes to certain Licensed Software resident in the Trepyx Equipment or Customer-Provided Equipment. If Trepyx has agreed to provide updates and changes, Trepyx may perform such updates and changes remotely or on-site, at Trepyx’s sole option. Customer hereby consents to, and shall provide free access for, such updates deemed reasonably necessary by Trepyx.
8.4 Ownership of Telephone Numbers and Addresses. Customer acknowledges that use of the Services does not give it any ownership or other rights in any telephone number or Internet/on-line addresses provided, including but not limited to Internet Protocol (“IP”) addresses, e-mail addresses and web addresses.
8.5 Intellectual Property Rights in the Services. Title and intellectual property rights to the Services are owned by Trepyx, its agents, suppliers or affiliates or their licensors or otherwise by the owners of such material. The copying, redistribution, reselling, bundling or publication of the Services, in whole or in part, without express prior written consent from Trepyx or other owner of such material, is prohibited.
</p>
<h5>ARTICLE 9. CONFIDENTIAL INFORMATION AND PRIVACY</h5>  
<p>
9.1 Disclosure and Use. All Confidential Information shall be kept by the receiving party in strict confidence and shall not be disclosed to any third party without the disclosing party’s express written consent. Notwithstanding the foregoing, such information may be disclosed (i) to the receiving party’s employees, affiliates, and agents who have a need to know for the purpose of performing this Agreement, using the Services, rendering the Services, and marketing related products and services (provided that in all cases the receiving party shall take appropriate measures prior to disclosure to its employees, affiliates, and agents to assure against unauthorized use or disclosure); or (ii) as otherwise authorized by this Agreement. Each party agrees to treat all Confidential Information of the other in the same manner as it treats its own proprietary information, but in no case using a degree of care less than a reasonable degree of care.
9.2 Exceptions. Notwithstanding the foregoing, each party’s confidentiality obligations hereunder shall not apply to information that: (i) is already known to the receiving party without a pre-existing restriction as to disclosure; (ii) is or becomes publicly available without fault of the receiving party; (iii) is rightfully obtained by the receiving party from a third party without restriction as to disclosure, or is approved for release by written authorization of the disclosing party; (iv) is developed independently by the receiving party without use of the disclosing party’s Confidential Information; or (v) is required to be disclosed by law or regulation.
9.3 Remedies. Notwithstanding any other Article of this Agreement, the non-breaching party shall be entitled to seek equitable relief to protect its interests pursuant to this Article 9, including, but not limited to, injunctive relief.
9.4 Monitoring. Trepyx shall have no obligation to monitor postings or transmissions made in connection with the Services, however, Customer acknowledges and agrees that Trepyx and its agents shall have the right to monitor any such postings and transmissions from time to time and to use and disclose them in accordance with this Agreement, and as otherwise required by law or government request. Trepyx reserves the right to refuse to upload, post, publish, transmit or store any information or materials, in whole or in part, that, in Trepyx’s sole discretion, is unacceptable, undesirable or in violation of this Agreement.
</p>
<h5>ARTICLE 9A: CUSTOMER PRIVACY POLICIES</h5>  
<p>
In addition to the provisions of Article 9, the privacy policy below applies to Trepyx’s handling of Customer confidential information. In the event of a conflict between the provisions of Article 9 and any provision of the privacy policy below, the applicable provision of the privacy policy shall prevail in the resolution of the conflict. A copy of Trepyx’s privacy policy is available at [url] (or any successor URL). 
9A.2 Privacy Note Regarding Information Provided to Third Parties: Trepyx is not responsible for any information provided by Customer to third parties, and this information is not subject to the privacy provisions of this Agreement or the privacy policies. Customer assumes all privacy and other risks associated with providing personally identifiable information to third parties via the Services.
</p>
<h5>ARTICLE 10. PROHIBITED USES</h5>  
<p>
10.1 Resale. Except as otherwise provided in the General Terms and Conditions, Customer may not sell, resell, sublease, assign, license, sublicense, share, provide, or otherwise utilize in conjunction with a third party (including, without limitation, in any joint venture or as part of any outsourcing activity) the Services or any component thereof.
10.2 Use Policies. Customer agrees to ensure that all uses of the Trepyx Equipment and/or the Services installed at its premises (“use”) are legal and appropriate. Specifically, Customer agrees to ensure that all uses by Customer or by any other person (“user”), whether authorized by Customer or not, comply with all applicable laws, regulations, and written and electronic instructions for use. Trepyx reserves the right to act immediately and without notice to terminate or suspend the Services and/or to remove from the Services any information transmitted by or to Customer or users, if Trepyx (i) determines that such use or information does not conform with the requirements set forth in this Agreement, (ii) determines that such use or information interferes with Trepyx’s ability to provide the Services to Customer or others, (iii) reasonably believes that such use or information may violate any laws, regulations, or written and electronic instructions for use. Furthermore, the Services shall be subject to one or more Acceptable Use Policies (“AUP”) that may limit use, or (iv) reasonably believes that Customer’s use of the Service interferes with or endangers the health and/or safety of Trepyx personnel or third parties. The AUP and other policies concerning the Services are posted on Trepyx’s web site(s) at [url] (or any successor URL) or on another web site about which Customer has been notified, and are incorporated to this Agreement by reference. Trepyx may update the use policies from time to time, and such updates shall be deemed effective seven (7) days after the update is posted online, with or without actual notice to Customer. Accordingly, Customer should check the above web addresses (or the applicable successor URLs) on a regular basis to ensure that its activities conform to the most current version of the use policies. Trepyx’s action or inaction in enforcing acceptable use shall not constitute review or approval of Customer’s or any other users’ use or information.
10.3 Violation. Any breach of this Article 10 shall be deemed a material breach of this Agreement. In the event of such material breach, Trepyx shall have the right to restrict, suspend, or terminate immediately any or all Service Orders, without liability on the part of Trepyx, and then to notify Customer of the action that Trepyx has taken and the reason for such action, in addition to any and all other rights and remedies under this Agreement.
</p>
<h5>ARTICLE 11. SERVICE LEVEL AGREEMENTS (SLA)</h5>  
<p>
Trepyx is committed to providing the highest level of Service to its Customers. The SLA defines the minimum Service expectations a Customer may expect from Trepyx Business Services. The remedies set forth in the SLA, which can be found on the Trepyx website at [url] (or any successor URL, “Website”), shall be the Customer’s sole and exclusive remedy for any Service Interruption in the Services, outage, unavailability, delay or other degradation in the Services or any Trepyx failure to meet the objectives of the Services. 

<h5>ARTICLE 12. INSURANCE</h5>  
<p>
12.1 Trepyx shall maintain during the Initial Term or any Renewal Term commercial general liability insurance that covers its liability and obligations hereunder including property damage and personal injury.
12.2 The liability limits under these policies shall be, at a minimum, one million ($1,000,000) dollars per occurrence, with a combined single limit for bodily injury and property damage liability.

<h5>ARTICLE 13. MISCELLANEOUS TERMS</h5>  
<p>
13.1 Force Majeure. Neither party shall be liable to the other party for any delay, failure in performance, loss, or damage to the extent caused by force majeure conditions such as acts of God, fire, explosion, power blackout, cable cut, acts of regulatory or governmental agencies, unavailability of right-of- way, unavailability of services or materials upon which the Services rely, or other causes beyond the party’s reasonable control, except that Customer’s obligation to pay for Services provided shall not be excused. Changes in economic, business or competitive condition shall not be considered force majeure events.
13.2 Assignment and Transfer. Neither Party shall assign any right, obligation or duty, in whole or in part, nor of any other interest hereunder, without the prior written consent of the other Party, which shall not be unreasonably withheld. The foregoing notwithstanding, Trepyx may assign this Agreement to any affiliate, related entity, or successor in interest without Customer’s consent. In addition, Trepyx may partially assign its rights and obligations hereunder to any party that acquires from Trepyx all or substantially all of the assets of a network(s) in which the Services is deployed to Customer. All obligations and duties of either Party under this Agreement shall be binding on all successors in interest and assigns of such Party.
13.3 Export Law and Regulation. Customer acknowledges that any products, software, and technical information (including, but not limited to, services and training) provided pursuant to the Agreement may be subject to U.S. export laws and regulations, and any foreign use or transfer of such products, software, and technical information must be authorized under those regulations. Customer agrees that it will not use distribute, transfer, or transmit the products, software, or technical information (even if incorporated into other products) except in compliance with U.S. export regulations. If requested by Trepyx, Customer also agrees to sign written assurances and other export-related documents as may be required for Trepyx to comply with U.S. export regulations.
13.4 Notices. Except as otherwise provided in this Agreement, any notices or other communications contemplated or required under this Agreement, in order to be valid, shall be in writing and shall be given via personal delivery, overnight courier, or via U.S. Certified Mail, Return Receipt Requested. Notices to Customer shall be sent to the Customer billing address; notices to Trepyx shall be sent to [address], Attn: Director of Business Customer Operations, with an email copy to: [email] Attn.: Senior Vice President & General Counsel. All such notices shall be deemed given and effective on the day when delivered by overnight delivery service or certified mail.
13.5 Entire Understanding. The Agreement constitutes the entire understanding of the parties related to the subject matter hereof. The Agreement supersedes all prior agreements, proposals, representations, statements, or understandings, whether written or oral, concerning the Services or the parties’ rights or obligations relating to the Services. Any prior representations, promises, inducements, or statements of intent regarding the Services that are not expressly provided for in this Agreement are of no effect. Terms or conditions contained in any purchase order, or restrictive endorsements or other statements on any form of payment, shall be void and of no force or effect. Only specifically authorized representatives of Trepyx may make modifications to this Agreement or this Agreement’s form. No modification to the form or this Agreement made by a representative of Trepyx who has not been specifically authorized to make such modifications shall be binding upon Trepyx. No subsequent agreement among the parties concerning the Services shall be effective or binding unless it is executed in writing by authorized representatives of both parties.
13.6 Tariffs. Notwithstanding anything to the contrary in the Agreement, Trepyx may elect or be required to file tariffs with regulatory agencies for certain Services. In such event, the terms set forth in the Agreement may, under applicable law, be superseded by the terms and conditions of the Tariffs. Without limiting the generality of the foregoing, in the event of any inconsistency with respect to rates, the rates and other terms set forth in the applicable Sales Order shall be treated as individual case based arrangements to the maximum extent permitted by law, and Trepyx shall take such steps as are required by law to make the rates and other terms enforceable. If Trepyx voluntarily or involuntarily cancels or withdraws a Tariff under which a Service is provided to Customer, the Service will thereafter be provided pursuant to the Agreement and the terms and conditions contained in the Tariff immediately prior to its cancellation or withdrawal. In the event that Trepyx is required by a governmental authority to modify a Tariff under which Service is provided to Customer in a manner that is material and adverse to either party, the affected party may terminate the applicable Sales Order upon a minimum thirty (30) days’ prior written notice to the other party, without further liability.
13.7 Construction. In the event that any portion of this Agreement is held to be invalid or unenforceable, the parties shall replace the invalid or unenforceable portion with another provision that, as nearly as possible, reflects the original intention of the parties, and the remainder of this Agreement shall remain in full force and effect.
13.8 Survival. The rights and obligations of either party that by their nature would continue beyond the expiration or termination of this Agreement or any Service Order, including without limitation representations and warranties, indemnifications, and limitations of liability, shall survive termination or expiration of this Agreement or any Service Order.
13.9 Choice of Law. The domestic law of the state [state] shall govern the construction, interpretation, and performance of this Agreement, except to the extent superseded by federal law.
13.10 No Third Party Beneficiaries. This Agreement does not expressly or implicitly provide any third party (including users) with any remedy, claim, liability, reimbursement, cause of action, or other right or privilege.
13.11 No Waiver. No failure by either party to enforce any rights hereunder shall constitute a waiver of such right(s).
13.12 Independent Contractors. The Parties to this Agreement are independent contractors. Neither Party is an agent, representative, or partner of the other Party. Neither Party shall have any right, power, or authority to enter into any agreement for, or on behalf of, or incur any obligation or liability of, or to otherwise bind, the other Party. This Agreement shall not be interpreted or construed to create an association, agency, joint venture, or partnership between the Parties or to impose any liability attributable to such a relationship upon either Party.
13.13 Article Headings. The article headings used herein are for reference only and shall not limit or control any term or provision of this Agreement or the interpretation or construction thereof.
13.14 Compliance with Laws. Each of the Parties agrees to comply with all applicable local, state and federal laws and regulations and ordinances in the performance of its respective obligations under this Agreement.
</p>    
<h5>ADDITIONAL TERMS APPLICABLE TO INTERNET SERVICES</h5>  
<p>
In addition to Articles 1 through 13 above, Articles 14 and 15A are specifically applicable to Internet Service:
ARTICLE 14: WEB HOSTING. If Customer submits a Service Order(s) for web hosting services, the following terms shall also apply:
14.1 Authorization. By using the Services to publish, transmit or distribute material or content, Customer (i) warrants that the material or content complies with the provisions of the Agreement, (ii) authorizes Trepyx, its agents and affiliates to reproduce, publish, distribute, and display such content worldwide and (iii) warrants that Customer has the right to provide such authorization. Customer acknowledges that material posted or transmitted using the Services may be copied, republished or distributed by third parties, and agrees to indemnify, defend and hold harmless Trepyx, its agents and affiliates for any harm resulting from such actions.
14.2 Web Site Content. If applicable, Trepyx will host Customer’s web site in a data center in accordance with Trepyx’s then-current published specifications, including, without limitation, storage levels (“Customer Web Site”). Ownership of all graphics, text, or other information or content materials supplied or furnished by Customer for incorporation into or delivery through a Customer Web Site shall remain with Customer (or the party that supplied such materials to Customer). Ownership of any software developed or modified by Trepyx and all graphics, text, or other information or content materials supplied or furnished by Trepyx for incorporation into a Customer Web Site shall remain with Trepyx (or the party that supplied such materials to Trepyx). Customer agrees that Trepyx has no proprietary, financial, or other interest in Customer's goods or services that may be described in or offered through a Customer Web Site, and that Customer is solely responsible for content quality, performance, and all other aspects of its goods or services and the information or other content contained in or provided through a Customer Web Site. Customer assumes all responsibility for use by others of the Customer Web Site (including commercial transactions, whether completed or not).
14.3 Web Site Backup and Restoration. Customer acknowledges and agrees that (i) it is responsible for developing and maintaining procedures (apart from the Services) to protect the Customer content, including, without limitation, making appropriate backup copies of the Customer content as may be necessary for reconstruction of any data, files, informational materials, or electronic messages; and (ii) Trepyx is not responsible for backup and restoration of Customer Content.
ARTICLE 14A: PROVISION OF SERVICE/USE. Subject to the terms and conditions herein, Internet Services are intended for commercial use only. Customer is prohibited from reselling Hospitality Internet Services, except that Customer may use such Services to provide internet service to its short-term lodging accommodation end users. Trepyx shall provide Hospitality Internet Service to a demarcation point at the Service Location. Customer shall be responsible for any and all facilities, equipment and/or devices required to use Hospitality Internet Services on the customer-side of the demarcation point.
ARTICLE 15. DOMAIN NAME REGISTRATION. If Customer submits a Service Order(s) for domain name registration services, the following terms shall also apply:</h5>  
15.1 Registration. At the request of Customer, Trepyx will use commercially reasonable efforts to facilitate the registration of the Customer internet domain name (“Customer Domain Name”) with a domain name registration service of Trepyx’s choosing, but only to the extent that Customer provides Trepyx with all necessary information relevant to such registration. The domain name registration service will invoice Customer directly for all applicable registration fees, maintenance fees, and other applicable fees related thereto. Customer hereby acknowledges that Customer is entirely responsible for the payment of any and all such fees. Trepyx does not represent that the Customer Domain Name will be available on an initial or ongoing basis. Further, Customer acknowledges that Customer, not Trepyx, has ownership, control, and use of the Customer Domain Name. Further, Customer hereby agrees now and forever to release and to hold harmless Trepyx, its employees, affiliates, agents, and contractors, from any and all losses, damages, rights, claims, and actions with respect to, or in any way arising from, the domain name registration service’s removal of allocation or support for the Customer Domain Name. Should Customer require modification of the Customer Domain Name or additional related services, additional charges may apply from the relevant registration service and from Trepyx for setup of the modification or addition.
15.2 Sub-Domain Name. Should Customer be unable to register a unique domain name, Trepyx may grant upon Customer request and only for the term of the Service Order providing for such service, the limited, personal, and non- transferable right to specify and append a sub-domain name to Trepyx’s prescribed domain name, for the sole purpose of uniquely identifying Customer’s e-mail address. Trepyx does not represent that Customer’s selected sub-domain name will be available. Customer receives no right to Trepyx’s domain name other that as specifically stated in this Article 15. Upon the termination of the applicable Service Order, Customer shall surrender all rights, privileges and interest in and to the sub- domain name and Trepyx’s domain name.
</p>

<h5>ADDITIONAL TERMS APPLICABLE TO VOICE SERVICES AND HOSPITALITY VOICE SERVICES</h5>  
<p>
In addition to provisions 1 THROUGH 13 above, the following Articles 16 through 20 are specifically applicable to Voice Services.
ARTICLE 16: USAGE BILLING
16.1 Voice Service calling plans billed as a flat monthly fee may not include certain call types. These excluded call types will instead be charged on a per-call basis (e.g., operator services) or a measured basis (e.g., international calls). Generally, for billing purposes, a measured call begins when the call is answered by the called party or an automated answering device (such as an answering machine or fax machine); it ends when one of the parties disconnects the call.
16.2 Except as otherwise provided in these General Terms and Conditions, Voice Service measured calls are recorded in whole minutes, with partial minutes rounded up to the next whole minute. If the computed charge for a measured call or for taxes or surcharges includes a fraction of a cent, the fraction is rounded up to the nearest whole cent.
16.3 Notwithstanding anything to the contrary in this Agreement, some providers (e.g., those involved in calls to foreign countries) charge for a completed call when the called party’s line rings or after a certain number of rings. If such a provider charges Trepyx or its Associated Parties, as if such a call were answered by the called party, Trepyx will charge Customer for a completed call. Voice Service, including Hospitality Voice Service, pricing lists and fees can be found at [url]. 
</p>
<h5>ARTICLE 17: USE POLICY</h5>  
<p>
17.1 Additional Use Restrictions. Except as otherwise provided in the General Terms and Conditions, Voice Service may only be used at Service Location(s) where such service is installed by Trepyx. Customer understands and acknowledges that if Customer attempts to install or use the Trepyx Equipment or Voice Service at another location, Voice Service, including but not limited to 911/E911, may fail to function or may function improperly. It will be considered a material violation of this Agreement if Customer moves Voice Service to another location without first notifying Trepyx. Customer expressly agrees not to use Voice Service for auto-dialing, continuous or extensive call forwarding, telemarketing, fax broadcasting or fax blasting, or for any other use that results in excessive usage inconsistent with standard commercial calling patterns. If Trepyx determines, in its sole discretion, that Customer’s use of Voice Service is excessive or in violation of this Agreement, Trepyx reserves the right, among other things, to terminate or modify Voice Service immediately and without notice. 
</p>
<h5>ARTICLE 17A: SERVICE LIMITATION</h5>  
<p>
17A.1 Disruption of Service. Customer acknowledges and understands that Voice Service will not be available for use under certain circumstances, including without limitation when the network or facilities are not operating or if normal electrical power to the MTA, ATA or ALG is interrupted and such equipment does not have a functioning backup. Customer also understands and acknowledges that the performance of the battery backup is not guaranteed. If the battery backup does not provide power, Voice Services will not function until normal power is restored. Customer also understands that certain online features of Voice Service, where such features are available, will not be available under certain circumstances, including but not limited to the interruption of the Internet connection.
17A.2 Provision of Service. Subject to the terms and conditions herein, Voice Services are intended for commercial use only. 
</p>
<h5>ARTICLE 18: LIMITATIONS OF 911/E911</h5>  
<p>
18.1 Limitations. Voice Services includes a 911/ Enhanced 911 function (“911/E911”) that may differ from the 911 or Enhanced 911 function furnished by other providers. As such, it may have certain limitations. CUSTOMER ACKNOWLEDGES AND ACCEPTS ANY LIMITATIONS OF 911/E911.
18.2 Correct Address. In order for Customer’s 911/E911 calls to be properly directed to emergency services, Trepyx must have Customer’s correct Service Location address. If Customer moves Voice Service to a different Service Location without Trepyx’s approval, 911/E911 calls may be directed to the wrong emergency authority, may transmit the wrong Service Location address, and/or Voice Service (including 911/E911) may fail altogether. Therefore, Customer must contact Trepyx at least five (5) days before moving Voice Service to a new Service Location. All changes in Service Location require Trepyx’s prior approval.
18.3 Service Interruptions. Customer acknowledges and understands that certain Voice Service uses the electrical power in Customer’s Service Location. If there is an electrical power outage, 911 calling may be interrupted if the battery backup in the associated MTA, ALA or ALG is not installed, fails, or is exhausted after several hours. Furthermore, calls, including calls to 911/E911, may not be completed if Customer exceeds its Voice Service and equipment configuration calling capacity or if there is a problem with network facilities, including network congestion, network/equipment/power failure, or another technical problem.
18.4 Suspension and Termination by Trepyx. Customer understands and acknowledges that Voice Service, including 911/E911, as well as all online features of Voice Service, where Trepyx make these features available, will be disabled if Customer’s account is suspended or terminated.
18.5 LIMITATION OF LIABILITY AND INDEMNIFICATION. CUSTOMER ACKNOWLEDGES AND AGREES THAT NEITHER Trepyx NOR ITS ASSOCIATED PARTIES WILL BE LIABLE FOR ANY VOICE SERVICE OUTAGE, INABILITY TO DIAL 911 USING THE SERVICES, AND/OR INABILITY TO ACCESS EMERGENCY SERVICE PERSONNEL. CUSTOMER AGREE TO DEFEND, INDEMNIFY, AND HOLD HARMLESS Trepyx AND ITS ASSOCIATED PARTIES FROM ANY AND ALL CLAIMS, LOSSES, DAMAGES, FINES, PENALTIES, COSTS, AND EXPENSES (INCLUDING BUT NOT LIMITED TO REASONABLE ATTORNEY FEES) BY, OR ON BEHALF OF, CUSTOMER OR ANY THIRD PARTY OR USER OF THE VOICE SERVICES RELATING TO THE FAILURE OR OUTAGE OF THE SERVICES, INCLUDING THOSE RELATED TO 911/E911.
</p>
ARTICLE 19: VOICE EQUIPMENT REQUIREMENTS
<p>
19.1 MTA. To use Voice Service, Customer will need a multimedia terminal adapter (“MTA”), application layer gateway (“ALG”), analog telephone adapter (“ATA”) or other adapter device. Customer can lease an MTA from Trepyx, in which case it will be Trepyx Equipment. Or, in some areas, Trepyx may permit Customer to use Voice Service with an MTA that Customer has purchased, in which case the MTA will be Customer Equipment. Customer agrees to keep the MTA plugged into a working electrical power outlet at all times.
19.2 Incompatible Equipment and Services. Customer acknowledges and understands Voice Service may not support or be compatible with:
(a) Non-recommended configurations including but not limited to MTAs, ATAs or ALGs not currently certified by Trepyx as compatible with Voice Service;
(b) Certain non-voice communications equipment, including certain makes or models of alarm and security systems, certain medical monitoring devices, certain fax machines, and certain “dial-up” modems;
(c) Rotary-dial phone handsets, pulse-dial phone handsets, and models of other voice-related communications equipment such as certain private branch exchange (PBX) equipment, answering machines, and traditional Caller ID units;
(d) Casual/dial around (10-10) calling; 976, 900, 700, or 500 number calling;
(e) 311, 511, or other x11 calling (other than 411 and 911); and
(f) Other call types not expressly set forth in Trepyx’s product literature (e.g., outbound shore-to-ship calling).
</p>
<h5>ARTICLE 20: ADDITIONAL LIMITATIONS ON Trepyx’S LIABILITY FOR VOICE SERVICE</h5>  
<p>
20.1 Limitations on Trepyx’s Liability for Directories and Directory Assistance for Voice Service Customers. THESE LIMITATIONS SHALL APPLY WHERE Trepyx MAKES AVAILABLE AN OPTION TO LIST CUSTOMER’S NAME, ADDRESS, AND/OR TELEPHONE NUMBER IN A PUBLISHED DIRECTORY OR DIRECTORY ASSISTANCE DATABASE, AND ONE OR MORE OF THE FOLLOWING CONDITIONS OCCURS: (i) CUSTOMER REQUESTS THAT CUSTOMER’S NAME, ADDRESS AND/OR PHONE NUMBER BE OMITTED FROM A DIRECTORY OR DIRECTORY ASSISTANCE DATABASE, BUT THAT INFORMATION IS INCLUDED IN EITHER OR BOTH; (ii) CUSTOMER REQUESTS THAT CUSTOMER’S NAME, ADDRESS AND/OR PHONE NUMBER BE INCLUDED IN A DIRECTORY OR DIRECTORY ASSISTANCE DATABASE, BUT THAT INFORMATION IS OMITTED FROM EITHER OR BOTH; OR (iii) THE PUBLISHED OR LISTED INFORMATION FOR CUSTOMER’S ACCOUNT CONTAINS MATERIAL ERRORS OR OMISSIONS. IF ANY OF THESE CONDITIONS PERTAIN, THEN THE AGGREGATE LIABILITY OF Trepyx AND ITS ASSOCIATED PARTIES SHALL NOT EXCEED THE MONTHLY CHARGES, IF ANY, WHICH CUSTOMER HAS ACTUALLY PAID TO Trepyx TO LIST, PUBLISH, NOT LIST, OR NOT PUBLISH THE INFORMATION FOR THE AFFECTED PERIOD. CUSTOMER SHALL HOLD HARMLESS Trepyx AND ITS ASSOCIATED PARTIES AGAINST ANY AND ALL CLAIMS FOR DAMAGES CAUSED OR CLAIMED TO HAVE BEEN CAUSED, DIRECTLY OR INDIRECTLY, BY THE ERRORS AND OMISSIONS REFERENCED ABOVE. FURTHERMORE, IF Trepyx MAKES AVAILABLE DIRECTORY ADVERTISING SERVICES, NEITHER Trepyx NOR ANY OF ITS ASSOCIATED PARTIES WILL BE LIABLE FOR ANY ACTS, ERRORS, OR OMISSIONS RELATED TO SUCH DIRECTORY ADVERTISING.
20.2 CUSTOMER INFORMATION. Trepyx and its suppliers reserve the right both during the term of this Agreement and upon its termination to delete Customer’s voicemail, call detail, data, files, or other information that is stored on Trepyx’s or its suppliers’ servers or systems, in accordance with our storage policies. Customer understands and acknowledges that Trepyx shall have no liability whatsoever as a result of the loss or removal of any such voicemail, call detail, data, files, or other information.
</p>
------------------------------------------------------------
<h5>ARTICLE 20A: ADDITIONAL TERMS APPLICABLE TO TOLL FREE SERVICES</h5>
In addition to Articles 1 THROUGH 13 and Articles 17 THROUGH 20, the following Article 20A is specifically applicable to Toll Free Services offered by Trepyx:
20A.1 Limitation. Subject to service availability, Customer may order Toll Free Services. Toll Free Services are not intended for residential use. In order to purchase and retain Toll Free Service with Trepyx, Customer must have Voice Services, and must map each Toll Free telephone number (“TFN”) to a Voice Service telephone number (“Associated TN”). If Customer terminates an Associated TN at any time during the Toll Free Services term, Customer must immediately: (1) map the applicable TFN to another Digital Voice telephone number on Customer’s Trepyx account, (2) purchase a new Digital Voice telephone number to map to the TFN, (3) port out the TFN to another toll free carrier; or (4) disconnect the TFN. If Customer fails to take immediate action as indicated above, Trepyx will disconnect the TFN. Trepyx shall have no liability for loss of Toll Free Services which results from Customer failing to take immediate action as indicated above.
 20A.2 Term and Termination. Toll Free Services are offered on a month to month basis. Customer shall have the right to terminate Toll Free Services, at any time, for any reason, upon thirty (30) days prior notice to Trepyx, subject to payment of all outstanding amounts due for the Toll Free Services and the return of any and all Trepyx Equipment. Termination of Toll Free Services is not subject to Termination Charges. Toll Free Services will terminate simultaneously with Customer’s Voice Services.
20A.3 Authorization. When ordering Toll Free Service, as set forth or referenced in each applicable Service Order Customer authorizes Trepyx to act as its agent in initiating and provisioning such Toll Free Service.
20A.4. Toll Free Charges
(a) Prices. Toll Free Service is subject to the toll free pricing identified in the applicable Service Order, or if none stated, subject to the pricing lists and fees found at [url]. 
(b) Billing Increments. Unless otherwise stated in a Service Order, usage-based charges will be billed on either a per-minute or per-message basis. Service calls invoiced on a per-minute basis will have an initial minimum call duration of one (1) minute, subsequent intervals of one (1) minute each, and will be billed by rounding to the next whole minute.
(c) Rounding of Charges. Trepyx reserves the right to round up any and all invoice amounts to the nearest one (1) cent.
(d) Provision of Service. Subject to the terms and conditions herein, Toll Free Services are intended for commercial use only.
</p>
------------------------------------------------------------
<h5>ARTICLE 20B: ADDITIONAL TERMS APPLICABLE TO TRUNK SERVICES</h5>  
<p>
In addition to provisions 1 THROUGH 13 and Articles 17, 19 AND 20 above, the following Article 20B is specifically applicable to Trunk Services offered by Trepyx:
20B.1 Limitation. Subject to service availability, Customer may order Trunk Services. Trunk Services are not intended for residential use.
20B.2 911 Notice for Trunk Services. Customer expressly acknowledges and agrees that it has reviewed, understands, and agrees to the terms set forth below.
(a) Customer action is essential to the protection of its employees and other users of the Trunk Services, as described below. Multi-line telephone systems, such as PBX systems, ordinarily only transmit the same, generic location information for all 911 calls placed from any handset connected to the PBX or other system. For example, in the case of a business with telephone extensions in three buildings and multiple floors in each building, the E911 call taker would only see the same main telephone number and location that the customer has identified, regardless of which station was used to place the call. If Customer does not take action as described below, fire, police and other emergency responders may be delayed or even prevented from timely reaching its location in response to a 911 call.
(b) Trepyx offers the opportunity for Customers to designate up to ten different zones within their premises that would be separately identified to the E911 call taker, such as a specific floor, side of a building, or other identifying information that could assist emergency responders to more quickly reach the appropriate location. To utilize this option, Customer must in the initial or a subsequent Service Order request the assignment of Emergency Location Information numbers and provide location information for each zone exactly as it should appear to the 911 call taker. For each zone requested, up to ten, Customer will receive a phone number that Trepyx will register in the 911 database or databases with the specific location information provided by Customer. Customer is solely responsible for programming its telephone system to map each station to one of these numbers, and for updating the system as necessary to reflect moves or additions of stations within the premises.
(c) Many states now require businesses using multi-line telephone systems to program their systems to transmit specific location information for 911 calls. Customer acknowledges and understands that it, and not Trepyx, bears sole responsibility to ensure that it identifies and complies with all such applicable laws, and any failure to do so is a breach of the Agreement. Customer represents, warrants and covenants that it will utilize the Trepyx Emergency Location Information numbers described above at least to the extent required by law, and that Customer does not require the use of more than ten different location identifiers or other features not currently offered under this Agreement in order to comply with applicable laws. Customer also warrants that it does not currently have “Private Switch/Automatic Location Identification” service in connection with its existing telephone service from another provider at the location(s) for which it has ordered Trunk Services from Trepyx.
(d) Trepyx will post only the main billing telephone number in the 911 database or databases using Customer’s billing address as the Registered Location, unless Customer requests the assignment of Emergency Location Information as set forth above. Customer must notify Trepyx at least five (5) days prior to moving the Trunk Service to another location. Customer acknowledges that if they move prior to providing such notice and a 911 call is placed using the Trunk Services, or if Customer when using Emergency Location Information numbers does not timely update their telephone system to account for internal moves, adds and changes, the E911 call taker may see incorrect or incomplete location information and the caller may need to confirm their actual location information to the call taker. (e) Some businesses elect to make test calls to 911 from multiple stations to verify that the 911 call taker receives the desired location information and is able to call back one or more of the telephone numbers that they receive to confirm it rings to the station from which the 911 call was placed. If Customer chooses to do so, it agrees to obtain prior approval from the relevant emergency communications center and assumes all responsibility for the placement of such calls.
20B.3 Recommended Battery Back-Up is NOT Included
Customer acknowledges and understands that the Trunk Services use the electrical power from the Service Location. Customer understands and acknowledges that they may lose access to and use of the Trunk Services, including 911/E911, if electrical power to the Integrated Access Device (IAD), PBX switch, and/or handsets is interrupted and such devices are not supported by a working battery backup. Customer also understands and acknowledges that Trepyx does not provide a battery backup for such devices and Customer is urged to arrange for their own backup power supply to these devices. In the event of a power outage, the duration of Trunk Service during a power outage using the Trepyx Equipment installed to provide Trunk Service will depend on Customer’s backup power choice. If the IAD is disconnected or removed and/or a battery is not charged, Trunk Service, including access to 911, will not be available. Customer acknowledges and agrees that in the event of a power failure, Trepyx bears no responsibility for such loss of service.
20B.4 Customer Responsibility for Telephone Equipment
(a) Customer is solely responsible for providing and maintaining working PBX equipment and handsets (Customer- Provided Equipment), notifying and training its users regarding proper use of the system in accordance with applicable, including regulatory, requirements, and for any programming to its telephone system that may be necessary to enable direct dialing of N11 numbers such as 911 and to enable calls to be connected to new area codes. Customer also acknowledges and accepts that Trepyx does not support seven- digit local calling even in areas of the country that still permit that option, and Customer will program its system as necessary to support ten-digit dialing for local calls.
(b) Trepyx shall not be responsible to the Customer if changes in any of the facilities, operations or procedures of Trepyx utilized in the provision of Trunk Service render any Customer-Provided Equipment or other equipment provided by a Customer obsolete or require modification or alteration of such equipment or system or otherwise affect its use or performance.
(c) Customer must arrange its Customer-Provided Equipment to provide for the interception of assigned but unused station numbers. A call intercepted by the attendant will be considered to be completed and subject to a charge for the call.
(d) Customer acknowledges and agrees that Trunk Service is not compatible with alarm and security systems, certain medical monitoring devices, certain fax machines, and certain “dial-up” modems. Customer’s attempt to use any such systems in connection with Trunk Services is solely at its own risk and Trepyx shall not be liable for any damages whatsoever for any non-operation or damage to such services or devices.
20B.5 Trunk Service Charges.
(a) Prices. Trunk Service is subject to the trunk service pricing identified in the applicable Service Order, and subject to the pricing lists and fees found at [url].  
(b) Billing Increments. Unless otherwise stated in a Service Order, domestic long distance calls, and in-bound domestic calls to toll-free numbers associated with Trunk Services will be billed on a per-minute or per-message basis. Service calls invoiced on a per-minute basis will have an initial minimum call duration of one (1) minute, subsequent intervals of one (1) minute each, and will be billed by rounding to the next whole minute. All other calls will be billed in accordance with the increments identified in the pricing lists and fees found at [url]. For purposes of this section, “domestic” means calls within the continental United States.
</p>


------------------------------------------------------------
<h5>ADDITIONAL TERMS APPLICABLE TO PRI SERVICES</h5>  
<p>
In addition to provisions 1 THROUGH 13 and Articles 17, 19, 20 and 20B above, the following Article xxx - xxx is specifically applicable to PRI Services offered by Trepyx:
21. Local Area. Notwithstanding anything to the contrary in the Agreement or in any Proposal, Customer acknowledges and agrees that Trepyx will provide Customer with PRIs to serve only one local calling area (LATA) per PRI at the Customer locations served by Trepyx under the Proposal(s).
22. Telephone Number Assignment. Customer shall assign telephone numbers from NPANXXs consistent with the Trepyx Rate Center associated with such NPANXX. Customer shall terminate only local calls to its PRIs and all calls shall be rated as if originated and terminated based on the Rate Center served by the Proposal (and the ILEC local calling scope and NPANXX associated with such Rate Center). Customer shall be responsible for all toll or long distance charges for Customer’s end users at the applicable Trepyx long distance rates set forth in Trepyx’s tariffs and/or price lists (including in instances where the Customer’s end users’ local calling area differs from the local calling area of the relevant ILEC, and including calls that are unauthorized and/or originated by fraudulent means).
23. Traffic Thresholds. If Customer's traffic is comprised of greater than twenty percent (20%) of traffic originating from and/or terminating to third parties other than the ILEC, an additional $0.02 penalty will be applied to all minutes exceeding this twenty percent (20%) threshold.
24. Signaling Information. Customer shall pass all signaling information it receives or generates associated with the traffic it sends to Trepyx, including but not limited to originating line information, such as Calling Party Number (“CPN”) and Automatic Number Identification (“ANI”) and shall require its end users to comply with legal requirements pertaining to caller identification. If Customer does not send Trepyx the correct signaling information or removes such information, including but not limited to CPN and ANI, Trepyx shall be entitled to charge Customer Trepyx’s tariffed per minute access charge rates associated with such traffic and shall also pass through any access or other charges assessed against Trepyx by any other carrier for such traffic. In addition, Trepyx reserves the right to terminate this Agreement immediately, cease providing any or all of the Services, and pursue any other remedies available to it if Customer does not send correct signaling information.
25. Reasonable Usage. Customer acknowledges that the charges for PRI Services ordered by Customer are based upon certain levels of usage. Trepyx shall have the right to require Customer to purchase additional PRIs from Trepyx if monthly traffic on a PRI exceeds 100,000 minutes per month or if the peak usage on a PRI exceeds 1,000 minutes per hour during normal business hours. At Trepyx’s option, if Customer does not cooperate with Trepyx to purchase such additional PRIs, Trepyx shall install such PRIs at its convenience and begin billing Customer for same or will charge Customer $.02 per minute on each minute of use over the threshold set forth in this Section. For purposes of this Agreement, the phrase “normal business hours” shall mean Monday through Friday from 9:00 AM to 6:00 PM Eastern Time.
26. Customer’s Responsibilities to Third Parties/Third Party Charges. Trepyx makes no representations or warranties regarding the relationship, responsibilities, or obligations Customer may have with any other service provider or telecommunications carrier with which Customer interconnects, either directly or indirectly, or through use of Trepyx’s Service(s). Unless otherwise set forth in a Proposal executed by the Parties, Customer is solely responsible for coordination of any and all third party services necessary for Customer’s use of Trepyx’s Services (“Third Party Services”). Customer acknowledges and agrees that Customer is solely responsible for identifying and paying any and all charges and expenses associated with any Third Party Services used by Customer in connection with Trepyx’s Services or due to Customer’s use of Trepyx Services, or Customer’s provision of service to end users, including, without limitation, any applicable monthly charges, usage charges, long distance charges, installation charges, nonrecurring charges, cross connection charges, applicable termination/cancellation charges, access charges, reciprocal compensation charges, and transiting charges, whether imposed pursuant to tariff, contract, or regulatory edict.
27. INDEMNIFICATION: SUBJECT TO THE TERMS AND CONDITIONS OF THIS AGREEMENT, CUSTOMER AGREES TO DEFEND, HOLD HARMLESS, AND INDEMNIFY THE OTHER PARTY, ITS EMPLOYEES, DIRECTORS, OFFICERS AND AGENTS, FROM AND AGAINST ALL CLAIMS, ACTIONS, DAMAGES, AND/OR LIABILITIES, TOGETHER WITH ANY AND ALL LOSSES, FINES, PENALTIES, COSTS, AND EXPENSES, INCLUDING, WITHOUT LIMITATION, ATTORNEYS’ FEES AND EXPENSES OR PENALTIES IMPOSED BY GOVERNMENTAL ENTITIES (COLLECTIVELY, THE "LIABILITIES") IN CONNECTION WITH ANY LITIGATION OR OTHER FORM OF ADJUDICATORY PROCEDURE, CLAIM, DEMAND, INVESTIGATION, OR FORMAL OR INFORMAL INQUIRY, OR ANY SETTLEMENT THEREOF, WHICH ARISES DIRECTLY OR INDIRECTLY FROM OR IN CONNECTION WITH THE NONFULFILLMENT OR BREACH OF ANY REPRESENTATION, WARRANTY, COVENANT, AGREEMENT, OR OBLIGATION OF CUSTOMER CONTAINED IN OR CONTEMPLATED BY THIS AGREEMENT. WITHOUT LIMITING THE FOREGOING, CUSTOMER’S OBLIGATION TO INDEMNIFY SPECIFICALLY INCLUDES: (I) ANY AND ALL LIABILITIES OF ANY KIND INCURRED BY Trepyx AS A RESULT OF ANY DISPUTE OR ERROR IN CUSTOMER’S CLASSIFICATION AS AN INFORMATION SERVICES PROVIDER AND/OR CLAIM OF EXEMPTION FROM ACCESS CHARGES ASSESSED ON THE TRAFFIC AND/OR CUSTOMER’S (OR CUSTOMER’S END USERS’) FAILURE TO PROPERLY IDENTIFY THE JURISDICTION OF TRAFFIC CARRIED OVER THE Trepyx SERVICES OR EXCHANGED WITH Trepyx; (II) ANY AND ALL LIABILITIES ARISING FROM USE OF Trepyx’S SERVICE BY CUSTOMER OR ITS END USERS; (III) ANY AND ALL LIABILITIES ARISING FROM ANY BREACH OF CUSTOMER’S REPRESENTATIONS AND WARRANTIES HEREUNDER; (IV) ANY AND ALL LIABILITIES ARISING FROM CONTENT; AND (V) ANY AND ALL LIABILITIES OF ANY KIND INCURRED BY Trepyx AS A RESULT OF ANY DISPUTE, ERROR OR VIOLATION OF THE FCC’S RULES AND POLICIES REGARDING LNP OR TELEPHONE NUMBERING RESOURCES.
28. REGULATORY REQUIREMENTS. Trepyx makes no representations or warranties of any kind With respect to the jurisdictional nature or regulatory classification of the traffic associated with Customer’s services to its end users that incorporate the Trepyx Services provided hereunder. Customer is responsible for identifying and complying with all Regulatory Requirements that may apply to Customer (whether now existing or that may exist during the course of this Agreement and any renewals thereof) and its services to its end users, including, but not limited to, Regulatory Requirements that pertain to: federal or state regulatory approvals or filing requirements; federal or state universal service fund contributions; and payment of federal, state, or local regulatory fees, franchise or license fees, and taxes. Trepyx RESERVES THE RIGHT TO INCREASE OR DECREASE RATES ON AT LEAST THIRTY (30) DAYS NOTICE. If any Regulatory Requirement has the effect of canceling, changing or superseding any material term with respect to the delivery of Service(s) (other than changes which are the subject of a rate increase as described in the foregoing sentence), then this Agreement will be deemed modified in such a way as the Parties mutually agree is consistent with the form, intent and purpose of this Agreement and is necessary to comply with the Regulatory Requirement. If the Parties cannot agree to modifications necessary to comply with a Regulatory Requirement within thirty (30) days after the Regulatory Requirement is effective, then either Party may terminate this Agreement and/or any Service(s) impacted by the Regulatory Requirement effective as of the date of such Party’s written notice to the other Party.
29. E911 Databases, CNAM and Directory Listings. Customer shall be responsible for provision of 911 and E911, CNAM and directory listing information and database updates to its end users without Trepyx’s assistance or intervention. Trepyx is not responsible for any losses, claims, demands, suits or any liability whatsoever, whether suffered, made, instituted or asserted by the Customer, Customer’s end users, or by any other party or person related to E911, CNAM, or Directory Listings.
30. Letters of Agency. Customer shall be responsible for providing Trepyx with letters of agency (“LOA”), compliant with state and federal slamming rules and regulations and satisfactory in both form and content to Trepyx, from Customer’s end users authorizing the applicable Service(s). Customer acknowledges that service will not be ported or activated unless and until said LOAs are received by Trepyx.
31. Law Enforcement. Customer shall be responsible for responding to all requests from law enforcement or other governmental agencies, whether transmitted through Trepyx or directly to Customer regarding information about Customer’s end users. Customer shall be responsible for complying with all Communications Assistance for Law Enforcement Act requirements and requests. Should Customer require Trepyx’s assistance with responding to law enforcement or other requests, Trepyx shall charge Customers its tariffed maintenance rates.
32. Local Number Portability. Customer is solely responsible for compliance with all applicable FCC rules and policies regarding LNP and telephone numbering resources, and shall, on a timely basis, provide to Trepyx, upon Trepyx’s request, with any and all requested utilization information, including copies of the Customer’s FCC Form 502s, for all telephone numbers provided by Trepyx to Customer pursuant to this Agreement. Upon request by Trepyx or a New Local Service Provider (“NLSP”), Customer shall, on a timely basis, provide Trepyx and the NLSP with the Customer Service Record (“CSR”) for any telephone number provided by Trepyx to Customer pursuant to this Agreement. Upon receipt of a Local Service Request (“LSR”) from a NLSP or a New Network Service Provider (“NNSP”), or from Trepyx on behalf of a NLSP or NNSP, Customer shall return a Firm Order Confirmation (“FOC”) or, in the event the LSR contains any error, a rejection and error notification to Trepyx and the NLSP or NNSP within 24 hours unless the Customer receives the request on Friday, Saturday, Sunday or a national holiday, in which case Customer shall return the FOC or rejection and error notification to Trepyx and the NLSP or NNSP within 24 hours of 9:00 am the next business day. Upon receipt of a LSR from a NLSP or NNSP for any telephone number provided by Trepyx to Customer pursuant to this Agreement, Trepyx shall forward the LSR to the Customer. If Customer receives an LSR from a NLSP, NNSP or Trepyx on behalf of a NLSP or NNSP but fails, on a timely basis, to return a FOC or rejection and error notification to the NLSP or NNSP and Trepyx, Trepyx may, at its sole discretion, return a FOC to the NLSP or NNSP on behalf of Customer.
</p>
  </div>
</template>

<script>
export default {

}
</script>

<style lang="scss">
p {
    width: 80%;
    margin: 1rem auto;
    line-height: 1.7rem;
    text-align: left;
}
</style>